//
// Generated file, do not edit! Created by nedtool 5.1 from veins/modules/application/platooning/messages/PlatoonInfo.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __PlATOONINFO_M_H
#define __PLATOONINFO_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0501
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
#include "ManeuverMessage_m.h"
// }}

/**
 * Class generated from <tt>veins/modules/application/platooning/messages/PlatoonInfo.msg:29</tt> by nedtool.
 * <pre>
 * // Request to move the correct position.
 * // Is sent from the leader of the Platoon to an accepted joiner.
 * // Needs a successful JoinResponse to be sent be before.
 * // Contains information about the Platoon and the position to join.
 * packet PlatoonInfo extends ManeuverMessage
 * {
 *     double platoonSpeed;
 *     int platoonLane;
 *     int newPlatoonFormation[];
 * }
 * </pre>
 */
class PlatoonInfo : public ::ManeuverMessage
{
  protected:
    double platoonSpeed;
    int platoonLane;
    int *newPlatoonFormation; // array ptr
    unsigned int newPlatoonFormation_arraysize;

  private:
    void copy(const PlatoonInfo& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const PlatoonInfo&);

  public:
    PlatoonInfo(const char *name=nullptr, short kind=0);
    PlatoonInfo(const PlatoonInfo& other);
    virtual ~PlatoonInfo();
    PlatoonInfo& operator=(const PlatoonInfo& other);
    virtual PlatoonInfo *dup() const override {return new PlatoonInfo(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual double getPlatoonSpeed() const;
    virtual void setPlatoonSpeed(double platoonSpeed);
    virtual int getPlatoonLane() const;
    virtual void setPlatoonLane(int platoonLane);
    virtual void setNewPlatoonFormationArraySize(unsigned int size);
    virtual unsigned int getNewPlatoonFormationArraySize() const;
    virtual int getNewPlatoonFormation(unsigned int k) const;
    virtual void setNewPlatoonFormation(unsigned int k, int newPlatoonFormation);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const PlatoonInfo& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, PlatoonInfo& obj) {obj.parsimUnpack(b);}


#endif // ifndef __PlatoonInfo_M_H

