//
// Generated file, do not edit! Created by nedtool 5.1 from veins/modules/application/platooning/messages/SendMTP.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __SENDMTP_M_H
#define __SENDMTP_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0501
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
#include "ManeuverMessage_m.h"
// }}

/**
 * Class generated from <tt>veins/modules/application/platooning/messages/SendMTP.msg:28</tt> by nedtool.
 * <pre>
 * // Response to a JoinRequest.
 * // Is sent from the leader of the Platoon to a possible joiner to answer a
 * // JoinRequest.
 * packet SendMTP extends ManeuverMessage
 * {
 *     // is the joiner allowed to join?
 *     bool request;
 * }
 * </pre>
 */
class SendMTP : public ::ManeuverMessage
{
  protected:
    bool request;

  private:
    void copy(const SendMTP& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const SendMTP&);

  public:
    SendMTP(const char *name=nullptr, short kind=0);
    SendMTP(const SendMTP& other);
    virtual ~SendMTP();
    SendMTP& operator=(const SendMTP& other);
    virtual SendMTP *dup() const override {return new SendMTP(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual bool getRequest() const;
    virtual void setRequest(bool request);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const SendMTP& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, SendMTP& obj) {obj.parsimUnpack(b);}


#endif // ifndef __JOINPLATOONRESPONSE_M_H

